#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent
import os

# Add block to configure servername and timezone when cloning/restoring
data = json.load(sys.stdin)
servername = data.get("servername")
timezone = data.get("timezone")
agent.set_env("ZBX_SERVER_NAME", servername)
agent.set_env("PHP_TZ", timezone)
agent.dump_env()

# Find default traefik instance for current node
default_traefik_id = agent.resolve_agent_id('traefik@node')
if default_traefik_id is None:
    sys.exit(2)

# Configure traefik virtual host
response = agent.tasks.run(
    agent_id=default_traefik_id,
    action='set-route',
    data={        
        'instance': os.environ['MODULE_ID'],
        'url': 'http://127.0.0.1:' + os.environ["TCP_PORT"],
        'lets_encrypt': os.environ.get("TRAEFIK_LETS_ENCRYPT",False),
        'host': os.environ.get("TRAEFIK_HOST","zabbix.domain.tld"),
        'http2https': os.environ.get("TRAEFIK_HTTP2HTTPS",False)
    },
)