#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

configure_retval = agent.tasks.run(agent_id=os.environ['AGENT_ID'], action='configure-module', data={
    "lets_encrypt": os.environ.get("TRAEFIK_LETS_ENCRYPT",False) == "True",
    "host": os.environ.get("TRAEFIK_HOST",""),
    "http2https": os.environ.get("TRAEFIK_HTTP2HTTPS",False) == "True",
    "servername": os.environ.get("ZBX_SERVER_NAME",""),
    "timezone": os.environ.get("PHP_TZ","")
})
agent.assert_exp(configure_retval['exit_code'] == 0, "The configure-module subtask failed!")